

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

song.stream.chunk-size=2548576

spring.ai.mistralai.api-key=
spring.ai.mistralai.chat.options.model=
spring.ai.chat.client.enabled=false
spring.ai.vectorstore.pinecone.api-key=
spring.ai.vectorstore.pinecone.index-name=


cloud.aws.credentials.access-key=
cloud.aws.credentials.secret-key=
cloud.aws.region.static=
aws.bucket=


spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
