spring.application.name=Orchestrator
spring.ai.google.genai.api-key=${AI_STUDIO_GEMINI}
spring.ai.google.genai.chat.options.google-search-retrieval=true
server.port=7456
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
# MySQL database connection URL
spring.datasource.url=${MYSQL_URL}
# MySQL database username
spring.datasource.username=${MYSQL_USER}
# MySQL database password
spring.datasource.password=${MYSQL_PASS}
spring.ai.chat.memory.repository.jdbc.initialize-schema=always
